spring:

  application:
    name: LogMeal

  datasource:
    url: <___>
    username: <___>
    password: <___>

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <___>
            client-secret: <___>

server:
  servlet:
    session:
      timeout: 20m

my-api-key: <___>