services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    spring-app:
      build:
        context: .
      environment:
        SPRING_PROFILES_ACTIVE: development
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
  #      SPRING_DATASOURCE_USERNAME: postgres
  #      SPRING_DATASOURCE_PASSWORD: postgres
      ports:
        - "8080:8080"
      depends_on:
        - postgres
volumes:
  postgres_data: