spring:
  application:
      name: demo

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <CLIENT_ID>
            client-secret: <CLIENT_SECRET>

apiKey: <API_KEY>