spring:
  application:
      name: demo

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your_id
            client-secret: your_secret

apiKey: your_key